# Generated by Django 5.2.7 on 2025-10-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_name", models.CharField(max_length=100)),
                ("api_endpoint", models.URLField()),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
