# Generated by Django 4.2.26 on 2026-02-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalintegration",
            name="api_key",
            field=models.CharField(
                blank=True, help_text="Encrypted API Key", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="externalintegration",
            name="last_sync_result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externalintegration",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("EMR", "Electronic Medical Records"),
                    ("PHARMACY_HUB", "External Pharmacy Hub"),
                    ("INSURANCE", "Insurance Gateway"),
                    ("LAB_EQUIPMENT", "Laboratory Equipment"),
                ],
                default="EMR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="externalintegration",
            name="status",
            field=models.CharField(default="Inactive", max_length=50),
        ),
    ]
