# Generated by Django 5.2.7 on 2026-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0002_externalintegration_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalintegration",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Encrypted API Key (use set_api_key/get_api_key methods)",
                max_length=512,
                null=True,
            ),
        ),
    ]
