# Generated by Django 6.0.6 on 2026-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0003_alter_externalintegration_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalintegration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="externalintegration",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externalintegration",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="externalintegration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
