# Generated by Django 4.2 on 2025-10-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "permissions": [
                    ("billing_view_invoice", "Can view invoice"),
                    ("billing_add_invoice", "Can add invoice"),
                    ("billing_change_invoice", "Can change invoice"),
                    ("billing_delete_invoice", "Can delete invoice"),
                ]
            },
        ),
    ]
