# Generated by Django 4.2 on 2025-10-16 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_invoice_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_date",
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
