# Generated by Django 5.2.7 on 2026-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_historicalinvoice_historicalpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoice",
            name="invoice_number",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=20
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
