# Generated by Django 6.0.6 on 2026-06-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_invoicecounter"),
        ("patients", "0008_alter_historicalpatient_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoice",
            name="insurance_claimed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="paid",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Credit/Debit Card"),
                    ("INSURANCE", "Insurance"),
                    ("ONLINE", "Online Payment"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="status",
            field=models.CharField(db_index=True, default="COMPLETED", max_length=20),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="transaction_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="insurance_claimed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="paid",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Credit/Debit Card"),
                    ("INSURANCE", "Insurance"),
                    ("ONLINE", "Online Payment"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(db_index=True, default="COMPLETED", max_length=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="invoice_total_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_date__gte", models.F("issue_date"))),
                name="invoice_due_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
    ]
