# Generated by Django 5.2.7 on 2026-04-07 17:45

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("medical_records", "0001_initial"),
        ("patients", "0007_alter_historicalpatient_emergency_contact_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientdocument",
            options={
                "permissions": [
                    ("medical_records_view_document", "Can view document"),
                    ("medical_records_add_document", "Can add document"),
                    ("medical_records_change_document", "Can change document"),
                    ("medical_records_delete_document", "Can delete document"),
                ]
            },
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientdocument",
            name="file",
            field=models.FileField(
                upload_to="patient_documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="HistoricalPatientDocument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("LAB_REPORT", "Lab Report"),
                            ("XRAY", "X-Ray"),
                            ("MRI", "MRI Scan"),
                            ("PRESCRIPTION", "Prescription"),
                            ("INSURANCE", "Insurance Document"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "file",
                    models.TextField(
                        max_length=100,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(blank=True, editable=False)),
                ("notes", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical patient document",
                "verbose_name_plural": "historical patient documents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
