# Generated by Django 4.2 on 2025-10-17 21:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "permissions": [
                    ("staff_view_staff", "Can view staff"),
                    ("staff_add_staff", "Can add staff"),
                    ("staff_change_staff", "Can change staff"),
                    ("staff_delete_staff", "Can delete staff"),
                ]
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="hire_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date when staff member was hired",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the staff member is currently active"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMERGENCY", "Emergency Department"),
                    ("CARDIOLOGY", "Cardiology"),
                    ("NEUROLOGY", "Neurology"),
                    ("ORTHOPEDICS", "Orthopedics"),
                    ("PEDIATRICS", "Pediatrics"),
                    ("SURGERY", "Surgery"),
                    ("ICU", "Intensive Care Unit"),
                    ("ONCOLOGY", "Oncology"),
                    ("RADIOLOGY", "Radiology"),
                    ("LABORATORY", "Laboratory"),
                    ("PHARMACY", "Pharmacy"),
                    ("ADMINISTRATION", "Administration"),
                    ("MAINTENANCE", "Maintenance"),
                    ("SECURITY", "Security"),
                    ("OTHER", "Other"),
                ],
                help_text="Department where staff member works",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Staff member's email address",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="first_name",
            field=models.CharField(
                help_text="Staff member's first name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="last_name",
            field=models.CharField(help_text="Staff member's last name", max_length=50),
        ),
        migrations.AlterField(
            model_name="staff",
            name="phone",
            field=models.CharField(
                help_text="Staff member's phone number",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("ADMIN", "Administrator"),
                    ("TECH", "Technician"),
                    ("PHARMACIST", "Pharmacist"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("SURGEON", "Surgeon"),
                    ("ANESTHESIOLOGIST", "Anesthesiologist"),
                    ("RADIOLOGIST", "Radiologist"),
                    ("LAB_TECH", "Laboratory Technician"),
                    ("SECURITY", "Security"),
                    ("MAINTENANCE", "Maintenance"),
                    ("OTHER", "Other"),
                ],
                help_text="Staff member's role/position",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="schedule",
            field=models.TextField(
                blank=True, help_text="Staff member's work schedule", null=True
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="staff_id",
            field=models.CharField(
                help_text="Unique staff identifier", max_length=20, unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("email",),
                name="unique_staff_email",
            ),
        ),
    ]
