# Generated by Django 4.2.26 on 2026-02-22 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0003_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="System user account associated with this staff member",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
