# Generated by Django 5.2.7 on 2026-03-24 02:35

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_staff_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStaff",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique staff identifier",
                        max_length=20,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Staff member's first name", max_length=50
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Staff member's last name", max_length=50
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "Doctor"),
                            ("NURSE", "Nurse"),
                            ("ADMIN", "Administrator"),
                            ("TECH", "Technician"),
                            ("PHARMACIST", "Pharmacist"),
                            ("RECEPTIONIST", "Receptionist"),
                            ("SURGEON", "Surgeon"),
                            ("ANESTHESIOLOGIST", "Anesthesiologist"),
                            ("RADIOLOGIST", "Radiologist"),
                            ("LAB_TECH", "Laboratory Technician"),
                            ("SECURITY", "Security"),
                            ("MAINTENANCE", "Maintenance"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Staff member's role/position",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMERGENCY", "Emergency Department"),
                            ("CARDIOLOGY", "Cardiology"),
                            ("NEUROLOGY", "Neurology"),
                            ("ORTHOPEDICS", "Orthopedics"),
                            ("PEDIATRICS", "Pediatrics"),
                            ("SURGERY", "Surgery"),
                            ("ICU", "Intensive Care Unit"),
                            ("ONCOLOGY", "Oncology"),
                            ("RADIOLOGY", "Radiology"),
                            ("LABORATORY", "Laboratory"),
                            ("PHARMACY", "Pharmacy"),
                            ("ADMINISTRATION", "Administration"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SECURITY", "Security"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Department where staff member works",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Staff member's phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Staff member's email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "schedule",
                    models.TextField(
                        blank=True, help_text="Staff member's work schedule", null=True
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="Date when staff member was hired",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the staff member is currently active",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="System user account associated with this staff member",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical staff",
                "verbose_name_plural": "historical staffs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
