# Generated by Django 5.2.7 on 2026-04-07 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_historicalstaff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaff",
            name="phone",
            field=models.CharField(
                help_text="Staff member's phone number",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="phone",
            field=models.CharField(
                help_text="Staff member's phone number",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
