# Generated by Django 4.2 on 2025-10-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labtest",
            options={
                "permissions": [
                    ("laboratory_view_labtest", "Can view lab test"),
                    ("laboratory_add_labtest", "Can add lab test"),
                    ("laboratory_change_labtest", "Can change lab test"),
                    ("laboratory_delete_labtest", "Can delete lab test"),
                ]
            },
        ),
    ]
