# Generated by Django 6.0.6 on 2026-06-09 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0004_hospitalservice"),
        ("laboratory", "0003_historicallabtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabtest",
            name="service",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"category": "LABORATORY"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hospital.hospitalservice",
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="service",
            field=models.ForeignKey(
                limit_choices_to={"category": "LABORATORY"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.hospitalservice",
            ),
        ),
        migrations.AlterField(
            model_name="historicallabtest",
            name="test_name",
            field=models.CharField(
                blank=True,
                help_text="Specific test name (overrides service name if provided)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="test_name",
            field=models.CharField(
                blank=True,
                help_text="Specific test name (overrides service name if provided)",
                max_length=100,
            ),
        ),
    ]
