# Generated by Django 6.0.6 on 2026-06-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0005_historicallabtest_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallabtest",
            name="created_at",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallabtest",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
