# Generated by Django 6.0.6 on 2026-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0006_alter_historicallabtest_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallabtest",
            name="created_at",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicallabtest",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
