# Generated by Django 5.2.7 on 2025-10-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=100)),
                ("dosage", models.CharField(max_length=50)),
                ("frequency", models.CharField(max_length=50)),
                ("prescribed_date", models.DateTimeField(auto_now_add=True)),
                ("prescribed_by", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
