# Generated by Django 4.2 on 2025-10-17 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staff_options_staff_hire_date_staff_is_active_and_more"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prescription",
            options={
                "permissions": [
                    ("pharmacy_view_prescription", "Can view prescription"),
                    ("pharmacy_add_prescription", "Can add prescription"),
                    ("pharmacy_change_prescription", "Can change prescription"),
                    ("pharmacy_delete_prescription", "Can delete prescription"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="prescription",
            name="prescribed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.staff",
            ),
        ),
    ]
