# Generated by Django 6.0.6 on 2026-06-09 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0004_hospitalservice"),
        ("pharmacy", "0003_historicalprescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprescription",
            name="service",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"category": "PHARMACY"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hospital.hospitalservice",
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Discontinued", "Discontinued"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="service",
            field=models.ForeignKey(
                limit_choices_to={"category": "PHARMACY"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.hospitalservice",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Discontinued", "Discontinued"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprescription",
            name="drug_name",
            field=models.CharField(
                blank=True,
                help_text="Specific medication name (overrides service name if provided)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="drug_name",
            field=models.CharField(
                blank=True,
                help_text="Specific medication name (overrides service name if provided)",
                max_length=100,
            ),
        ),
    ]
