# Generated by Django 4.2 on 2025-10-17 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0004_alter_patient_address_alter_patient_admission_date_and_more",
        ),
        ("staff", "0002_alter_staff_options_staff_hire_date_staff_is_active_and_more"),
        ("care_monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientcare",
            options={
                "ordering": ["-monitoring_date"],
                "permissions": [
                    ("care_monitoring_view_patientcare", "Can view patient care"),
                    ("care_monitoring_add_patientcare", "Can add patient care"),
                    ("care_monitoring_change_patientcare", "Can change patient care"),
                    ("care_monitoring_delete_patientcare", "Can delete patient care"),
                ],
            },
        ),
        migrations.AddField(
            model_name="patientcare",
            name="blood_pressure_diastolic",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Diastolic blood pressure (mmHg)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(150),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patientcare",
            name="blood_pressure_systolic",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Systolic blood pressure (mmHg)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(250),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patientcare",
            name="heart_rate",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Heart rate (beats per minute)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patientcare",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in centimeters",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(250.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patientcare",
            name="monitored_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who recorded the monitoring",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="patientcare",
            name="oxygen_saturation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Oxygen saturation percentage",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patientcare",
            name="respiratory_rate",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Respiratory rate (breaths per minute)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(8),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patientcare",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Body temperature in Celsius",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(35.0),
                    django.core.validators.MaxValueValidator(45.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patientcare",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kilograms",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(500.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patientcare",
            name="monitoring_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time of monitoring"
            ),
        ),
        migrations.AlterField(
            model_name="patientcare",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes and observations", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patientcare",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient being monitored",
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="patientcare",
            name="status",
            field=models.CharField(
                choices=[
                    ("STABLE", "Stable"),
                    ("CRITICAL", "Critical"),
                    ("IMPROVING", "Improving"),
                    ("DETERIORATING", "Deteriorating"),
                    ("DISCHARGED", "Discharged"),
                    ("OBSERVATION", "Under Observation"),
                ],
                help_text="Patient's current status",
                max_length=20,
            ),
        ),
    ]
