# Generated by Django 5.2.7 on 2026-03-24 02:50

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care_monitoring", "0002_alter_patientcare_options_and_more"),
        ("patients", "0006_historicalpatient"),
        ("staff", "0005_historicalstaff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPatientCare",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            ("CRITICAL", "Critical"),
                            ("IMPROVING", "Improving"),
                            ("DETERIORATING", "Deteriorating"),
                            ("DISCHARGED", "Discharged"),
                            ("OBSERVATION", "Under Observation"),
                        ],
                        help_text="Patient's current status",
                        max_length=20,
                    ),
                ),
                (
                    "monitoring_date",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date and time of monitoring",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Body temperature in Celsius",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(35.0),
                            django.core.validators.MaxValueValidator(45.0),
                        ],
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Heart rate (beats per minute)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Systolic blood pressure (mmHg)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Diastolic blood pressure (mmHg)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                (
                    "respiratory_rate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Respiratory rate (breaths per minute)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Oxygen saturation percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kilograms",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(500.0),
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(250.0),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes and observations",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monitored_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Staff member who recorded the monitoring",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="staff.staff",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Patient being monitored",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical patient care",
                "verbose_name_plural": "historical patient cares",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
