# Generated by Django 6.0.6 on 2026-06-09 06:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care_monitoring", "0003_historicalpatientcare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatientcare",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in centimeters",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("250.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientcare",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kilograms",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("500.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patientcare",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in centimeters",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("250.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patientcare",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kilograms",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("500.0")),
                ],
            ),
        ),
    ]
