# Generated by Django 4.2 on 2025-10-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surgery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surgery",
            options={
                "permissions": [
                    ("surgery_view_surgery", "Can view surgery"),
                    ("surgery_add_surgery", "Can add surgery"),
                    ("surgery_change_surgery", "Can change surgery"),
                    ("surgery_delete_surgery", "Can delete surgery"),
                ]
            },
        ),
        migrations.AddConstraint(
            model_name="surgery",
            constraint=models.UniqueConstraint(
                fields=("operating_room", "scheduled_date"),
                name="unique_operating_room_schedule",
            ),
        ),
    ]
