# Generated by Django 4.2 on 2025-10-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "permissions": [
                    ("reporting_view_report", "Can view report"),
                    ("reporting_add_report", "Can add report"),
                    ("reporting_change_report", "Can change report"),
                    ("reporting_delete_report", "Can delete report"),
                ]
            },
        ),
    ]
