# Generated by Django 4.2 on 2025-10-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={
                "permissions": [
                    ("inventory_view_inventoryitem", "Can view inventory item"),
                    ("inventory_add_inventoryitem", "Can add inventory item"),
                    ("inventory_change_inventoryitem", "Can change inventory item"),
                    ("inventory_delete_inventoryitem", "Can delete inventory item"),
                ]
            },
        ),
    ]
