# Generated by Django 4.2 on 2025-10-17 21:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventoryitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="cost_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per unit",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date when item was added to inventory",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="expiry_date",
            field=models.DateField(
                blank=True, help_text="Expiry date for perishable items", null=True
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="supplier",
            field=models.CharField(
                blank=True, help_text="Supplier name", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("MEDICAL_SUPPLIES", "Medical Supplies"),
                    ("PHARMACEUTICALS", "Pharmaceuticals"),
                    ("EQUIPMENT", "Medical Equipment"),
                    ("CONSUMABLES", "Consumables"),
                    ("SURGICAL_INSTRUMENTS", "Surgical Instruments"),
                    ("LABORATORY", "Laboratory Supplies"),
                    ("OFFICE_SUPPLIES", "Office Supplies"),
                    ("MAINTENANCE", "Maintenance Supplies"),
                    ("PPE", "Personal Protective Equipment"),
                    ("OTHER", "Other"),
                ],
                help_text="Category of the inventory item",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="Last updated timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(
                help_text="Name of the inventory item", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="Current quantity in stock",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="reorder_level",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum quantity before reordering",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("PIECE", "Piece"),
                    ("BOX", "Box"),
                    ("PACK", "Pack"),
                    ("BOTTLE", "Bottle"),
                    ("VIAL", "Vial"),
                    ("TUBE", "Tube"),
                    ("KG", "Kilogram"),
                    ("GRAM", "Gram"),
                    ("LITER", "Liter"),
                    ("ML", "Milliliter"),
                    ("SET", "Set"),
                    ("OTHER", "Other"),
                ],
                help_text="Unit of measurement",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 0)),
                name="inventory_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                check=models.Q(("reorder_level__gte", 0)),
                name="inventory_reorder_level_non_negative",
            ),
        ),
    ]
