# Generated by Django 6.0.6 on 2026-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventoryitem_cost_per_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
