# Generated by Django 4.2 on 2025-10-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "permissions": [
                    ("appointments_view_appointment", "Can view appointment"),
                    ("appointments_add_appointment", "Can add appointment"),
                    ("appointments_change_appointment", "Can change appointment"),
                    ("appointments_delete_appointment", "Can delete appointment"),
                ]
            },
        ),
    ]
