# Generated by Django 4.2 on 2025-10-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("patient", "doctor", "appointment_date"),
                name="unique_appointment",
            ),
        ),
    ]
