# Generated by Django 6.0.6 on 2026-06-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_historicalappointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="arrived_at",
            field=models.DateTimeField(
                blank=True, help_text="Time when patient arrived at clinic", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalappointment",
            name="arrived_at",
            field=models.DateTimeField(
                blank=True, help_text="Time when patient arrived at clinic", null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Waiting", "Waiting/Arrived"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                db_index=True,
                default="Scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Waiting", "Waiting/Arrived"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                db_index=True,
                default="Scheduled",
                max_length=20,
            ),
        ),
    ]
