# Generated by Django 4.2 on 2025-10-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("ward", "room_number"), name="unique_room_per_ward"
            ),
        ),
    ]
