# Generated by Django 4.2 on 2025-10-18 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_ward_name_room_unique_room_per_ward"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={
                "permissions": [
                    ("hospital_view_room", "Can view room"),
                    ("hospital_add_room", "Can add room"),
                    ("hospital_change_room", "Can change room"),
                    ("hospital_delete_room", "Can delete room"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="ward",
            options={
                "permissions": [
                    ("hospital_view_ward", "Can view ward"),
                    ("hospital_add_ward", "Can add ward"),
                    ("hospital_change_ward", "Can change ward"),
                    ("hospital_delete_ward", "Can delete ward"),
                ]
            },
        ),
    ]
