# Generated by Django 6.0.6 on 2026-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_alter_room_options_alter_ward_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("LABORATORY", "Laboratory Test"),
                            ("RADIOLOGY", "Radiology/Imaging"),
                            ("SURGERY", "Surgical Procedure"),
                            ("ACCOMMODATION", "Ward/Room Charge"),
                            ("PHARMACY", "Medication/Pharmacy"),
                            ("OTHER", "Other Services"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hospital Service",
                "verbose_name_plural": "Hospital Services",
                "ordering": ["category", "name"],
            },
        ),
    ]
