# Generated by Django 4.2 on 2025-10-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "permissions": [
                    ("patients_view_patient", "Can view patient"),
                    ("patients_add_patient", "Can add patient"),
                    ("patients_change_patient", "Can change patient"),
                    ("patients_delete_patient", "Can delete patient"),
                ]
            },
        ),
    ]
