# Generated by Django 4.2 on 2025-10-17 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_ward_name_room_unique_room_per_ward"),
        ("patients", "0003_alter_patient_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(help_text="Patient's address"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(
                blank=True, help_text="Hospital admission date and time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(help_text="Patient's date of birth"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="discharge_date",
            field=models.DateTimeField(
                blank=True, help_text="Hospital discharge date and time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Patient's email address",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact phone number",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(help_text="Patient's first name", max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                help_text="Patient's gender",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_provider",
            field=models.CharField(
                blank=True,
                help_text="Insurance provider name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(help_text="Patient's last name", max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(
                blank=True, help_text="Patient's medical history", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                help_text="Patient's phone number",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned room",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.room",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="unique_id",
            field=models.CharField(
                help_text="Unique patient identifier", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned ward",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.ward",
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("discharge_date__isnull", True),
                    ("discharge_date__gte", models.F("admission_date")),
                    _connector="OR",
                ),
                name="discharge_after_admission",
            ),
        ),
    ]
