# Generated by Django 4.2.26 on 2026-02-22 12:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_alter_room_options_alter_ward_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0005_alter_patient_address_alter_patient_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPatient",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique patient identifier",
                        max_length=20,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Patient's first name", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Patient's last name", max_length=50),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="Patient's date of birth"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("P", "Prefer not to say"),
                        ],
                        help_text="Patient's gender",
                        max_length=1,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Patient's address", null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Patient's phone number",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Patient's email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "insurance_provider",
                    models.CharField(
                        blank=True,
                        help_text="Insurance provider name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact phone number",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, help_text="Patient's medical history", null=True
                    ),
                ),
                (
                    "admission_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Hospital admission date and time",
                        null=True,
                    ),
                ),
                (
                    "discharge_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Hospital discharge date and time",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Assigned room",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hospital.room",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Assigned ward",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hospital.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical patient",
                "verbose_name_plural": "historical patients",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
