# Generated by Django 5.2.7 on 2026-04-07 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_historicalpatient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatient",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact phone number",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Patient's phone number",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Emergency contact phone number",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Patient's phone number",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
