# Generated by Django 6.0.6 on 2026-06-09 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_alter_historicalpatient_emergency_contact_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatient",
            name="date_of_birth",
            field=models.DateField(db_index=True, help_text="Patient's date of birth"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Patient's email address",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="first_name",
            field=models.CharField(
                db_index=True, help_text="Patient's first name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                db_index=True,
                help_text="Patient's gender",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="last_name",
            field=models.CharField(
                db_index=True, help_text="Patient's last name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Patient's phone number",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(db_index=True, help_text="Patient's date of birth"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Patient's email address",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(
                db_index=True, help_text="Patient's first name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                db_index=True,
                help_text="Patient's gender",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(
                db_index=True, help_text="Patient's last name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Patient's phone number",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
