# Generated by Django 6.0.6 on 2026-06-15 19:37

import django.core.validators
import django.utils.timezone
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_alter_historicalpatient_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatient",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="address",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="Patient's address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="email",
            field=encrypted_model_fields.fields.EncryptedEmailField(
                blank=True, help_text="Patient's email address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="emergency_contact_phone",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Emergency contact phone number",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="insurance_provider",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Insurance provider name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="medical_history",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="Patient's medical history", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="phone",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Patient's phone number",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="Patient's address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=encrypted_model_fields.fields.EncryptedEmailField(
                blank=True, help_text="Patient's email address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Emergency contact phone number",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_provider",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Insurance provider name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="Patient's medical history", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Patient's phone number",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally with a leading +.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
