# Generated by Django 5.2.7 on 2026-04-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0001_initial"),
        ("patients", "0007_alter_historicalpatient_emergency_contact_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-sent_at"],
                "permissions": [
                    ("notifications_view_notification", "Can view notification"),
                    ("notifications_add_notification", "Can add notification"),
                    ("notifications_change_notification", "Can change notification"),
                    ("notifications_delete_notification", "Can delete notification"),
                ],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.CharField(
                help_text="Phone number or email address", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("RETRYING", "Retrying"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
